config/routes.rb
Rails.application.routes.draw do
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, presence: true
	validates :nid, presence: true
	validates :name, format: { with: /\A[a-zA-Z]+\z/, message: "Solo Se Permiten Letras en El Campo Nombre" }
	validates :nid, numericality: { only_integer: true }
	validates :main_tlf, numericality: { only_integer: true }
	validates :sec_tlf, numericality: { only_integer: true }
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "Nuevo Usuario Registrado." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "Registro Actualizado Exitosamente." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "El Registro ha sido eliminado." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:user_type, :nid, :date_e, :date_v, :name, :email, :main_tlf, :sec_tlf)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Siscobank</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :'Tipo de Persona' %>
    <select name="user_type">
      <option value="N">Natural</option>
      <option value="J">Juridico</option>
    </select> 
  </div>

  <div class="field">
    <%= form.label :'Numeroo de Documento' %>
    <%= form.number_field :nid %>
  </div>

  <div class="field">
    <%= form.label :'Fecha de Emision' %>
    <%= form.date_select :date_e %>
  </div>

  <div class="field">
    <%= form.label :'Fecha de Vencimiento' %>
    <%= form.date_select :date_v %>
  </div>

  <div class="field">
    <%= form.label :'Nombre' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :'Correo Electronico' %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :'Nro Telefonico Principal' %>
    <%= form.number_field :main_tlf %>
  </div>

  <div class="field">
    <%= form.label :'Numero Telefonico Secundario' %>
    <%= form.number_field :sec_tlf %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table class="table">
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Numero de Documento</th>
      <th>Fecha Emision</th>
      <th>Fecha Vencimiento</th>
      <th>Nombre</th>
      <th>Correo</th>
      <th>tlf Principal</th>
      <th>Tlf Secundario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.user_type.capitalize() %></td>
        <td><%= user.nid %></td>
        <td><%= user.date_e.strftime("%d/%m/%Y")%></td>
        <td><%= user.date_v.strftime("%d/%m/%Y") %></td>
        <td><%= user.name.titleize() %></td>
        <td><%= user.email %></td>
        <td><%= user.main_tlf %></td>
        <td><%= user.sec_tlf %></td>
        <td><%= link_to 'Ver', user %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <td><%= link_to 'Eliminar', user, method: :delete, data: { confirm: 'Seguro desea Eliminar el Registro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p class="text-danger">
  <strong>Tipo de Persona:</strong>
  <%= @user.user_type.titleize() %>
</p>

<p>
  <strong>Numerpo de Documento:</strong>
  <%= @user.nid %>
</p>

<p>
  <strong>Fecha de Emision:</strong>
  <%= @user.date_e.strftime("%d/%m/%Y") %>
</p>

<p>
  <strong>Fecha de Vencimiento:</strong>
  <%= @user.date_v.strftime("%d/%m/%Y")%>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @user.name.titleize() %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Telefono Principal:</strong>
  <%= @user.main_tlf %>
</p>

<p>
  <strong>Telefono Secundario:</strong>
  <%= @user.sec_tlf %>
</p>

<%= link_to 'Editar', edit_user_path(@user) %> |
<%= link_to 'Volver', users_path %>